export const userConstants = {
    GET_ALL_USERS_REQUEST : 'GET_ALL_USERS_REQUEST',
    GET_ALL_USERS_SUCCESS : 'GET_ALL_USERS_SUCCESS',
    GET_ALL_USERS_FAILURE : 'GET_ALL_USERS_FAILURE',

    ADD_USER_REQUEST : 'ADD_USER_REQUEST',
    ADD_USER_SUCCESS : 'ADD_USER_SUCCESS',
    ADD_USER_FAILURE : 'ADD_USER_FAILURE',

    DELETE_USER_REQUEST : 'DELETE_USER_REQUEST',
    DELETE_USER_SUCCESS : 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILURE : 'DELETE_USER_FAILURE',

    EDIT_USER_REQUEST : 'EDIT_USER_REQUEST',
    EDIT_USER_SUCCESS : 'EDIT_USER_SUCCESS',
    EDIT_USER_FAILURE : 'EDIT_USER_FAILURE',
}
